In [101]:
import numpy as np

import geatpy as ea

In [102]:
def constraint(Vars):
    w_num = np.zeros((Vars.shape[0], 1))
    w_sum = np.zeros((Vars.shape[0], 1))
    
    for i in range(Vars.shape[0]):
        rows = Vars[i, :]
        num_rows = np.where(rows != 0, 1, 0)
        w_num[i] = np.sum(num_rows)
        w_sum[i] = np.sum(rows)
    
    print("====================================CONSTRAINTS====================================")
    print("------------------------------------Vars------------------------------------")
    print(Vars)
    print("------------------------------------NUM------------------------------------")
    print(w_num)
    print("------------------------------------SUM------------------------------------")
    print(w_sum)
    
    return w_num, w_sum

In [103]:
class MyProblem(ea.Problem):

    def __init__(self):
        name = 'MyProblem'
        M = 1
        maxormins = [-1]
        Dim = 100
        varTypes = [0] * Dim
        lb = [0] * Dim
        ub = [1] * Dim
        lbin = [1] * Dim
        ubin = [1] * Dim
        
        ea.Problem.__init__(self,
                            name,
                            M,
                            maxormins,
                            Dim,
                            varTypes,
                            lb,
                            ub,
                            lbin,
                            ubin)

    def evalVars(self, Vars):
        # f = np.ones((Vars.shape[0], 1))
        # for i in range(Vars.shape[1]):
        #     column = Vars[:, [i]]
        #     filtered_column = np.where(column != 0, column, 1)
        #     f *= filtered_column
            
        f = np.ones((Vars.shape[0], 1))
        for i in range(Vars.shape[0]):
            rows = Vars[i, :]
            for j in range(len(rows)):
                w = rows[j]
                if w != 0:
                    f[i] *= w * (j+1) # remove * (j+1)
        
        print(f)

        CV = np.hstack(
            [np.abs(constraint(Vars)[0] - 10), np.abs(constraint(Vars)[1] - 1)])
        return f, CV

In [104]:
if __name__ == '__main__':
    problem = MyProblem()

    algorithm = ea.soea_SEGA_templet(
        problem,
        ea.Population(Encoding='RI', NIND=5000),
        MAXGEN=500,
        logTras=100)
    algorithm.mutOper.F = 0.7
    algorithm.recOper.XOVR = 0.7

    res = ea.optimize(algorithm,
                      verbose=True,
                      drawing=1,
                      outputMsg=True,
                      drawLog=True)
    print(res)

[[1.58544946e+110]
 [3.07602760e+115]
 [3.31154762e+110]
 ...
 [1.50983310e+117]
 [1.86675203e+112]
 [3.69290996e+110]]
====================================CONSTRAINTS====================================
------------------------------------Vars------------------------------------
[[0.54916382 0.57635498 0.16952515 ... 0.50558472 0.50463867 0.55783081]
 [0.50262451 0.08877563 0.36709595 ... 0.1803894  0.74032593 0.26004028]
 [0.59970093 0.89172363 0.56082153 ... 0.86886597 0.34542847 0.52871704]
 ...
 [0.26220703 0.87289429 0.30285645 ... 0.62817383 0.37149048 0.01324463]
 [0.68920898 0.70855713 0.45550537 ... 0.07629395 0.80181885 0.1187439 ]
 [0.02099609 0.25473022 0.73352051 ... 0.28692627 0.43185425 0.5697937 ]]
------------------------------------NUM------------------------------------
[[100.]
 [100.]
 [100.]
 ...
 [100.]
 [100.]
 [100.]]
------------------------------------SUM------------------------------------
[[48.27059937]
 [48.79858398]
 [48.64230347]
 ...
 [51.69692993]
 [48

Traceback (most recent call last):
  File "c:\Tool\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\jiawe\AppData\Local\Temp\ipykernel_28280\3257975438.py", line 12, in <module>
    res = ea.optimize(algorithm,
  File "c:\Tool\Python3\lib\site-packages\geatpy\optimize.py", line 104, in optimize
    [optPop, lastPop] = algorithm.run(prophetPop)
  File "c:\Tool\Python3\lib\site-packages\geatpy\algorithms\soeas\GA\SEGA\soea_SEGA_templet.py", line 76, in run
    self.call_aimFunc(offspring)  # 计算目标函数值
  File "c:\Tool\Python3\lib\site-packages\geatpy\Algorithm.py", line 209, in call_aimFunc
    self.problem.evaluation(pop)  # 调用问题类的evaluation()
  File "c:\Tool\Python3\lib\site-packages\geatpy\Problem.py", line 218, in evaluation
    return_object = self.evalVars(pop.Phen)
  File "C:\Users\jiawe\AppData\Local\Temp\ipykernel_28280\297555271.py", line -1, in evalVars
KeyboardInterrupt

Dur